name: Acceptance Tests

on: push

jobs:
  run-acceptance-tests:
    uses: hashicorp/vault-workflows-common/.github/workflows/acc-tests.yaml@98df3033eeef94112c1c4efca6689119c3c6b2d8
    secrets: inherit